### ISSUE TITLE
xmldsig dependency not mentioned

### ISSUE THREAD

**Issue by spaceone** [rohe/pysaml2#238]
xmldsig is nowhere mentioned as dependency. It is used in example/sp-wsgi/sp.py.
Why is it needed? It is not easy to get it in debian as it has a lot of dependencies.

**Comment by rohe** [comment]
An error in sp.py then because xmldsig is part of pysaml2.
Will fix.

On 15 Jul 2015, at 19:32, spaceone <notifications@github.com<mailto:notifications@github.com>> wrote:


xmldsig is nowhere mentioned as dependency. It is used in example/sp-wsgi/sp.py.
Why is it needed? It is not easy to get it in debian as it has a lot of dependencies.

-

**Comment by spaceone** [comment]
Fixed in https://github.com/rohe/pysaml2/commit/e341cdc5fe2f0a0c47b94c1a58d38ac03786db34
