### ISSUE TITLE
Pysaml2 and GAE

### ISSUE THREAD

**Issue by kmarkiv** [rohe/pysaml2#292]
I would like to to know if pysaml2 can be deployed on Google App engine. I can install python packages in my application to support this library but I will not be able to install C packages. I have noticed that some C packages are needed for supporting xml libraries. I was wondering if pysaml2 can work without me installing any of those. 

Thanks in advance and good work.

**Comment by rohe** [comment]
> 1 dec 2015 kl. 01:41 skrev Vikram <notifications@github.com>:
> 
> I would like to to know if pysaml2 can be deployed on Google App engine. I can install python packages in my application to support this library but I will not be able to install C packages. I have noticed that some C packages are needed for supporting xml libraries. I was wondering if pysaml2 can work without me installing any of those.

Right now I would say no.

The problem is that there is no pure ’complete’ Python implementation of XML security.
And I see no coming in the future.

So, if you don’t need support for XML signing and/or encryption then you might actually
get something working on GAE but to me that is a big ’if’.

> Thanks in advance and good work.

Thanks,

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett

**Comment by skortchmark9** [comment]
If it has dependencies on C packages, I think you can't really bill this as a "pure python" implementation. We were considering this library precisely because installing C dependencies is really annoying. Since your last post, have you encountered a python implementation of xml?

**Comment by Rob1080** [comment]
Hi, I'm also interested in using saml2 on google appengine standard environment.  
I found this library: https://github.com/XML-Security/signxml; does it meet the requirement for pure python  implementation of xml sig? 
Thanks
Rob

**Comment by vsgobbi** [comment]
I don't think so, since it uses "cryptography.hazmat.primitives", it's a C extended lib for python signxml
