### ISSUE TITLE
Attribute statement ignored

### ISSUE THREAD

**Issue by enriquepablo** [rohe/pysaml2#353]
I'm using pysaml2 4.0.5  (from djangosaml-0.14.4) and I'm finding a problem (in an SP setup) with authn responses received from IdPs, where the `Response` object that pysaml2 uses to represent the response from the IdP provides a `session_info` that that an empty `ava` attribute, even though the XML received from the IdP contains an `AttributeStatement`.

I have reproduced this error in a test, that can be seen here:

https://github.com/enriquepablo/pysaml2/compare/master...enriquepablo:eperez-failure?expand=1

I'm I (or djangosaml2) doing something wrong, or is  this a bug in pysaml2?

**Comment by enriquepablo** [comment]
What I've found is that the attribute names in the authn responses sent by the IdPs (likewise in the response I've included with the test) are the "display names", and the attribute converters try to find those as keys in the attribute maps and fail (in `pysaml2.attribute_converter.AttributeCopnverter.ava_from`).

There are tests in pysaml2 that take a saml2 authn response with the same form as those sent by the IdPs, i.e. attribute names like `cn`, `sn`, `uid` (see [1]), and loads the data in a different way (not using `client.parse_authn_request_response`) and get it right, see for example [2].


1.- https://github.com/enriquepablo/pysaml2/blob/master/tests/saml2_signed.xml
2.- https://github.com/enriquepablo/pysaml2/blob/master/tests/test_44_authnresp.py#L97

**Comment by rebeckag** [comment]
Great that you've already found it!

As you mention pysaml2 expects the `Name` of an attribute to be a full URN, i.e. `Name="urn:mace:dir:attribute-def:sn"` instead of `Name="sn"` in the `Attribute`:

```xml
<ns1:Attribute Name="urn:mace:dir:attribute-def:sn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
  <ns1:AttributeValue xsi:type="xs:string">Perez</ns1:AttributeValue>
</ns1:Attribute>
```
So right now it thinks your example only contains an unknown attribute `sn` in the `AttributeStatement` and ignores it.

A way around this is to [add custom mapping rules in the attribute maps](https://github.com/rebeckag/pysaml2/commit/8d3360e9c8f110df07e8aa6c6cd36265952ae9cd) [configured for the SP](https://github.com/rebeckag/pysaml2/blob/8d3360e9c8f110df07e8aa6c6cd36265952ae9cd/tests/server_conf.py#L38).
Hope this helps!

**Comment by enriquepablo** [comment]
Thanks for your solution Rebecka!

I'll follow your advice, and close the issue.
