### ISSUE TITLE
using this to login to existing saml enabled site

### ISSUE THREAD

**Issue by achapkowski** [rohe/pysaml2#397]
Can I leverage this package to login to a site that already is setup to use SAML based security?  
I am having a bit of trouble figuring that out.
If so, can someone please point me to some docs on how to do that?

Thank you

**Comment by jkakavas** [comment]
Hi, 

You can use pysaml2 as a SAML Identity Provider, in order to authenticate to a site/service that implements a SAML Service Provider. 

I would start from https://en.wikipedia.org/wiki/SAML_2.0#Web_Browser_SSO_Profile . Then take a look at the examples directory, for one of the idp (Identity Provider) examples.
